---
title: Exploring Modern Web Development
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A collection of experiments, projects, and learnings across front-end engineering, real-time data visualization, and web performance optimization.
show_downloads: false
google_analytics: 
theme: jekyll-theme-cayman
